/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package datagenerator

class App {
    List<String> _firstNames = ['Michael', 'Paul', 'Amy', 'George', 'John', 'Thomas'] 
    List<String> _lastNames = ['Mabin', 'Anderson', 'Washington', 'Jefferson', 'Adams', 'Simpson', 'Smithers',
       'Burns', 'Cartman', 'Bravlovski', 'Marsh']
    Random random
    String getGreeting() {
        return 'Hello world.'
    }

    public App() {

       // Create new randomizer
       random = new Random()
    }

    public String getFirstName() {
       Collections.shuffle _firstNames
       _firstNames.first()
    }

    public String getLastName() {
       Collections.shuffle _lastNames
       _lastNames.first()
    }

    public int nextInt(int range) {
       random.nextInt(range)
    }

    public String digits(int length) {
        // Returns a string of digits for specified length
        def numString = ''
        length.times { numString += random.nextInt(9).toString() }
        numString
    }

    static void main(String[] args) {
        App app = new App()
        println app.getGreeting()
        10.times {
            println app.getFirstName() + ' ' +  app.getLastName()
            println app.nextInt(100)
            println app.digits(9)
        }
    }
}
