/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package datagenerator

class Datagenerator {
    List<String> _firstNames = ['Michael', 'Paul', 'Amy', 'George', 'John', 'Thomas'] 
    List<String> _lastNames = ['Mabin', 'Anderson', 'Washington', 'Jefferson', 'Adams', 'Simpson', 'Smithers',
       'Burns', 'Cartman', 'Bravlovski', 'Marsh']
    Random random
    String getGreeting() {
        return 'Hello world.'
    }

    public Datagenerator() {

       // Create new randomizer
       random = new Random()
    }

    public String getFirstName() {
       Collections.shuffle _firstNames
       _firstNames.first()
    }

    public String getLastName() {
       Collections.shuffle _lastNames
       _lastNames.first()
    }

    public int nextInt(int range) {
       random.nextInt(range)
    }

    public String digits(int length) {
        // Returns a string of digits for specified length
        def numString = ''
        length.times { numString += random.nextInt(9).toString() }
        numString
    }

    public String alpha(int length) {
        // Returns a string of letters for specified lengh
        char[] alphabet = "abcdefghijklmnopqrstuvwxyz".toCharArray()
        def alphaString = ''
        length.times { alphaString += alphabet[random.nextInt(25)] }
        alphaString
    }

    static void main(String[] args) {
        Datagenerator dg = new Datagenerator()
        println dg.getGreeting()
        10.times {
            println dg.getFirstName() + ' ' +  dg.getLastName()
            println dg.nextInt(100)
            println dg.digits(9)
            println dg.alpha(11)
        }
    }
}
